### ISSUE TITLE
Change in performance since latest update (1.2.5)

### ISSUE THREAD

**Issue by kruimel0** [athombv/com.aeotec#35] opened 2017-01-02 10:36 UTC
Since last update, my Multisensor 6 appears to be 'out of range', while unaltered in position. Could this have to do anything with either the last Aeotec update or with the last Homey update (I'm on experimental and up-to-date)?

**Comment by RobinBol** [comment] 2017-01-04 17:26
That can not be caused by an update of the app, and very unlikely that it is caused by a Homey firmware update. Most likely is that something in the surroundings has changed that affects the range.

Will close this issue as it is not specific to the Aeotec app.

**Comment by mruiter** [comment] 2017-01-04 18:03
I and some others have also reported a massive decrease in z-wave range or Maybee mesh trouble. It started around firmware 1.0.4


I also never had a red ring my whole Homey live. A year now. 

Now I even sometimes get a red ring during pair. Something definitely is wrong with zwave since 1.0.4. I already reported this to emile and send in a log file. No real response to that until now. 


But for the record. More people are reporting this issue on zwave


Outlook voor Android






On Wed, Jan 4, 2017 at 6:26 PM +0100, "Robin Bolscher" <notifications@github.com> wrote:












That can not be caused by an update of the app, and very unlikely that it is caused by a Homey firmware update. Most likely is that something in the surroundings has changed that affects the range.


Will close this issue as it is not specific to the Aeotec app.

**Comment by RobinBol** [comment] 2017-01-04 19:04
Assigned @WeeJeWel as this is not app related.

**Comment by busscher** [comment] 2017-01-21 21:05
I share the same experience with z-wave / aeotec devices. Very bad z-wave range. I don't know when this was happen. With an app update of Aeotec or homey firmware. My presumption is after Homey firmware 1.1.0

**Comment by RobinBol** [comment] 2017-09-25 16:56
Closing this issue since it is rather old, we have had many iterations of Homey firmware. If the issue still exists please create an issue in the Homey issue tracker: https://github.com/athombv/homey/issues

**Closed by RobinBol** 2017-09-25 16:56 UTC
