### ISSUE TITLE
Smart Switch 6 always off in the Homey Card

### ISSUE THREAD

**Issue by n-peters** [athombv/com.aeotec#74] opened 2017-08-17 09:01 UTC
I've got a problem with the Smart Switch 6. When i turn it on, leave the page in the browser, then go back and view the card, it's turned off again, but still using power. The switch is also on at that time.

So the slider is switched to the left and the card is lightgrey again, while the switch is turned on actually. This is the same for the android app.

I'm at the latest 1.5 fw version, but the problem also occured in v1.3.

**Comment by CyberSponk** [comment] 2017-08-25 04:41
Same with Aeotec Smart Switch5 since Honey 1.5.0-rc8 and Aeotec 1.5.2, same with Aeotec 1.5.3. See also: https://forum.athom.com/discussion/3659/app-aeotec-by-athom-main-discussion-topic/p7

**Comment by CyberSponk** [comment] 2017-09-02 04:19
The problem also exits in 1.5.0 with noch rc / Version after 1.5.0-rc8 and Aeotec 1.5.3:
https://forum.athom.com/discussion/3659/app-aeotec-by-athom-main-discussion-topic/p8

**Comment by n-peters** [comment] 2017-09-09 06:17
I also noticed a lot of z-wave commands for this device:

[2017-09-09T06:16:05.662Z] Node[12]: Received application command for COMMAND_CLASS_METER, data: 0x0221740000000000000000000000000000
[2017-09-09T06:16:06.329Z] Node[12]: Received application command for COMMAND_CLASS_METER, data: 0x0221740000000000000000000000000000
[2017-09-09T06:16:06.592Z] Node[12]: Received application command for COMMAND_CLASS_METER, data: 0x0221740000000000000000000000000000
[2017-09-09T06:16:06.693Z] Node[12]: Received application command for COMMAND_CLASS_METER, data: 0x0221740000000000000000000000000000
[2017-09-09T06:16:06.826Z] Node[12]: Received application command for COMMAND_CLASS_METER, data: 0x0221740000000000000000000000000000
[2017-09-09T06:16:06.885Z] Node[12]: Received application command for COMMAND_CLASS_METER, data: 0x0221740000000000000000000000000000
[2017-09-09T06:16:15.113Z] Node[12]: Received application command for COMMAND_CLASS_METER, data: 0x02216400009aef000f00009aef00000000
[2017-09-09T06:16:15.229Z] Node[12]: Received application command for COMMAND_CLASS_METER, data: 0x02216400009aef000f00009aef00000000
[2017-09-09T06:16:15.442Z] Node[12]: Received application command for COMMAND_CLASS_METER, data: 0x02216400009aef000f00009aef00000000
[2017-09-09T06:16:16.378Z] Node[12]: Received application command for COMMAND_CLASS_METER, data: 0x02216400009aef000f00009aef00000000
[2017-09-09T06:16:17.028Z] Node[12]: Received application command for COMMAND_CLASS_METER, data: 0x02216400009aef000f00009aef00000000
[2017-09-09T06:16:17.083Z] Node[12]: Received application command for COMMAND_CLASS_METER, data: 0x02216400009aef000f00009aef00000000
[2017-09-09T06:16:17.640Z] Node[12]: Received application command for COMMAND_CLASS_METER, data: 0x02216400009aef000f00009aef00000000
[2017-09-09T06:16:20.407Z] Node[12]: Received application command for COMMAND_CLASS_METER, data: 0x0221740000000000000000000000000000
[2017-09-09T06:16:20.494Z] Node[12]: Received application command for COMMAND_CLASS_METER, data: 0x0221740000000000000000000000000000
[2017-09-09T06:16:21.564Z] Node[12]: Received application command for COMMAND_CLASS_METER, data: 0x0221740000000000000000000000000000
[2017-09-09T06:16:21.831Z] Node[12]: Received application command for COMMAND_CLASS_METER, data: 0x0221740000000000000000000000000000
[2017-09-09T06:16:21.874Z] Node[12]: Received application command for COMMAND_CLASS_METER, data: 0x0221740000000000000000000000000000
[2017-09-09T06:16:22.100Z] Node[12]: Received application command for COMMAND_CLASS_METER, data: 0x0221740000000000000000000000000000
[2017-09-09T06:16:22.783Z] Node[12]: Received application command for COMMAND_CLASS_METER, data: 0x0221740000000000000000000000000000

**Comment by RobinBol** [comment] 2017-09-11 13:10
Hi all, thanks for reporting this issue. I looked into the cause of this issue, and it seems that the device does not respond with an acknowledgement when Homey sends a command. This means that there is no way of knowing whether the command was successfully executed on the device, hence Homey assumes the worst and resets the state to before sending the 'failed' command. I am afraid this is a bug in the Smart Switch and perhaps you could turn to Aeotec to see if this is a known bug. For now I will close this issue as it does not seem to be fixable on our side.

**Closed by RobinBol** 2017-09-11 13:10 UTC
