### ISSUE TITLE
Fix ZW095 integration (all possible clamp configurations)

### ISSUE THREAD

**Issue by tillole** [athombv/com.aeotec#100] opened 2018-03-08 02:50 UTC
I have 2 pieces. Aeotec zw095 3 phase 4 wires ver. 1.4
homey finds these but then there is a message unknown device i use Aeotec app ver.1.6.4

**Comment by specialcircumstances** [comment] 2018-04-30 21:25
@tillole - working on a restructure of HEMs, so hopefully all generations will work soon.
You are welcome to test: https://github.com/specialcircumstances/com.aeotec

**Comment by RobinBol** [comment] 2018-07-02 13:56
Closing as duplicate of https://github.com/athombv/homey/issues/2288.

**Closed by RobinBol** 2018-07-02 13:56 UTC
Labels: bug
